version: '3.1'
volumes:
  postgres_test_data:
    external:
      name: dockerlearnittwiceapi_postgres_test_data
services:
  postgres_test:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: learnittwice_test
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5433:5432
    container_name: postgres_test